name: CICD

on:
  push: 
    branches: [main]
env:
  USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
  PASSWORD: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - name: CHECKOUT SOURCE
        uses: actions/checkout@v3
      - name:  LOGIN TO DOCKER HUB
        uses: docker/login-action@v3
        with:
          username: ${{env.USERNAME}}
          password: ${{env.PASSWORD}}
      - name: BUILD DOCKER Image
        run: Docker build -t psrs1981/nodejs-to-ec2 .
      - name: PUBLISH IMAGE TO DOCKER HUB
        run: docker push psrs1981/nodejs-to-ec2:latest

  deploy:
    needs: build
    runs-on: [aws-ec2]
    steps:
      - name: PULL IMAGE FROM DOCKER HUB
        run: docker pull psrs1981/nodejs-to-ec2:latest
      - name: DELETE EXISTING CONTAINER
        run: docker rm -f nodejs-to-ec2-container
      - name: RUN DOCKER CONTAINER
        run: docker run -d -p 3000:3000 nodejs-to-ec2-container psrs1981/nodejs-to-ec2


